### ISSUE TITLE
X509 TBS Cert + Self sign

### ISSUE THREAD

**Issue by macOS26** [w8wjb/ASN1Codable#1]
Hi,

Do you have a code example on creating an X509 TBS Cert + Self Signing?

I see there is an example for a CSR and signing in the tests, but not a corresponding one for the TBS. Thank you in advance. Looking forward to trying your Library out.

**Comment by w8wjb** [comment]
I added a `Certificate.sign(privateKey:algorithm:)` method and a unit test example. Hopefully that should do what you were looking for?

**Comment by macOS26** [comment]
That looks good to me! Thanks for adding that example / test.

**Comment by StarPlayrX** [comment]
I got it to create a cert, when used with a Smart Card it fails to extract the publicKey.  I'll follow up with some example code showing where it errors out.
